global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.31.36.89:9090','172.31.35.50:9100','172.31.39.149:9100','172.31.33.207:9100']
 
